// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    detalhe_loja: {
        name: "detalhe_loja";
        parameters: {
          /** BIGINT - use sql.bigint() */
          nu_ec: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          nu_ec: number;
          /** @sqlType STRING */
          nm_loja: string;
          /** @sqlType STRING */
          nm_razao_social: string;
          /** @sqlType STRING */
          tp_pessoa: string;
          /** @sqlType STRING */
          nm_ramo: string;
          /** @sqlType STRING */
          sg_uf: string;
          /** @sqlType STRING */
          nm_municipio: string;
          /** @sqlType STRING */
          ds_endereco: string;
          /** @sqlType INT */
          qt_dias_afiliacao: number;
          /** @sqlType DOUBLE */
          vl_faturamento: number;
          /** @sqlType DOUBLE */
          pc_chargeback: number;
          /** @sqlType INT */
          in_socio_pep: number;
          /** @sqlType INT */
          in_alteracao_societaria: number;
          /** @sqlType BIGINT */
          posicao_fila: number;
          /** @sqlType DOUBLE */
          score_pld: number;
          /** @sqlType STRING */
          faixa_risco: string;
          /** @sqlType INT */
          fl_fraude_confirmada: number;
          /** @sqlType BIGINT */
          fl_novo_suspeito: number;
          /** @sqlType STRING */
          principais_sinais: string;
          /** @sqlType INT */
          grau: number;
          /** @sqlType DOUBLE */
          pagerank: number;
          /** @sqlType BIGINT */
          qt_lojas_componente: number;
          /** @sqlType BIGINT */
          qt_raizes_componente: number;
          /** @sqlType BIGINT */
          qt_outras_lojas_fraude_componente: number;
          /** @sqlType BIGINT */
          qt_triangulos: number;
          /** @sqlType INT */
          dist_fraude: number;
          /** @sqlType DOUBLE */
          pct_vizinhos_fraude: number;
          /** @sqlType INT */
          fl_conta_compartilhada: number;
          /** @sqlType INT */
          fl_socio_comum_fraude: number;
          /** @sqlType BIGINT */
          qt_ciclos_pix: number;
          /** @sqlType BIGINT */
          qt_contas_liquidacao: number;
          /** @sqlType BIGINT */
          qt_socios: number;
        }>;
      };
    fila_risco: {
        name: "fila_risco";
        parameters: {
          /** STRING - use sql.string() */
          faixa: SQLStringMarker;
          /** STRING - use sql.string() */
          somente_novos: SQLStringMarker;
          /** STRING - use sql.string() */
          busca: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          posicao_fila: number;
          /** @sqlType BIGINT */
          nu_ec: number;
          /** @sqlType STRING */
          nm_loja: string;
          /** @sqlType STRING */
          nm_ramo: string;
          /** @sqlType STRING */
          sg_uf: string;
          /** @sqlType DOUBLE */
          score_pld: number;
          /** @sqlType STRING */
          faixa_risco: string;
          /** @sqlType INT */
          fl_fraude_confirmada: number;
          /** @sqlType BIGINT */
          fl_novo_suspeito: number;
          /** @sqlType STRING */
          principais_sinais: string;
          /** @sqlType BIGINT */
          qt_lojas_componente: number;
          /** @sqlType INT */
          fl_conta_compartilhada: number;
          /** @sqlType INT */
          fl_socio_comum_fraude: number;
          /** @sqlType BIGINT */
          qt_ciclos_pix: number;
          /** @sqlType INT */
          dist_fraude: number;
        }>;
      };
    kpis_risco: {
        name: "kpis_risco";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          qt_lojas: number;
          /** @sqlType BIGINT */
          qt_alto: number;
          /** @sqlType BIGINT */
          qt_novos_suspeitos: number;
          /** @sqlType BIGINT */
          qt_fraude_confirmada: number;
          /** @sqlType BIGINT */
          qt_grupos_suspeitos: number;
          /** @sqlType STRING */
          ts_atualizacao: string;
        }>;
      };
    rede_loja: {
        name: "rede_loja";
        parameters: {
          /** BIGINT - use sql.bigint() */
          nu_ec: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          src: string;
          /** @sqlType STRING */
          src_tipo: string;
          /** @sqlType STRING */
          src_nome: string;
          /** @sqlType INT */
          src_fraude: number;
          /** @sqlType DOUBLE */
          src_score: number;
          /** @sqlType STRING */
          src_faixa: string;
          /** @sqlType STRING */
          dst: string;
          /** @sqlType STRING */
          dst_tipo: string;
          /** @sqlType STRING */
          dst_nome: string;
          /** @sqlType INT */
          dst_fraude: number;
          /** @sqlType DOUBLE */
          dst_score: number;
          /** @sqlType STRING */
          dst_faixa: string;
          /** @sqlType STRING */
          relacao: string;
          /** @sqlType BIGINT */
          qt: number;
          /** @sqlType DOUBLE */
          valor: number;
        }>;
      };
    risco_por_ramo: {
        name: "risco_por_ramo";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          ramo: string;
          /** @sqlType BIGINT */
          novos_suspeitos: number;
          /** @sqlType BIGINT */
          fraude_confirmada: number;
        }>;
      };
    top_lojas_alto: {
        name: "top_lojas_alto";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType BIGINT */
          nu_ec: number;
          /** @sqlType STRING */
          nm_loja: string;
          /** @sqlType DOUBLE */
          score_pld: number;
          /** @sqlType BIGINT */
          fl_novo_suspeito: number;
          /** @sqlType INT */
          fl_fraude_confirmada: number;
        }>;
      };
  }
}
